dir-path: "../aac_data"
preprocessed-dir-path: "../aac_data_preprocessed"
dialog-dir-path: "../aac_dialogi"
speakleash-datasets:
  - "plwiki"
  - "1000_novels_corpus_CLARIN-PL"
  - "open_subtitles_corpus"
  - "wolne_lektury_corpus"
  - "web_artykuły_inne_148"
  - "web_artykuły_inne_147"
  - "web_artykuły_inne_118"
  - "web_artykuły_inne_150"
  - "web_artykuły_inne_153"
  - "web_artykuły_inne_1"
huggingface-dataset-url: "hf://datasets/WiktorS/polish-news/full_data.csv"
huggingface-dataset-name: "hugging_face_news"
data-limit: 100000
conversations-id-file: "../aac_dialogi/Conversations.xls"
conversations-train-dir-name: "train"
conversations-test-dir-name: "test"